# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  include:
    - master
    - refs/tags/

stages:
  - stage: Build
    jobs:
      - job: build
#        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              VERSION_TAG=`git describe --tags`
              echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
              echo $(VERSION_TAG)
#          - task: Docker@2
#            displayName: Login to Docker Hub
#            inputs:
#              command: login
#              containerRegistry: DockerHub
#          - task: Docker@2
#            displayName: Build and Push
#            inputs:
#              command: buildAndPush
#              repository: analyse4/hedwig
#              tags: $(Build.SourceVersion)

